<?php
// Function to generate the report system content
function report_system_shortcode() {
    ob_start(); // Start output buffering

    // HTML structure for the report system, you can add your custom content here
    ?>
    <div class="report-system">
        <h1>Report System</h1>
        <!-- Add any report form or functionality here -->
    
    </div>
    <?php

    return ob_get_clean(); // Get the content generated by the buffer and return it
}

// Register the shortcode
add_shortcode('report_system', 'report_system_shortcode');
?>
