<?php
// Function to generate the report system content
function report_system_shortcode() {
    ob_start(); // Start output buffering

    // HTML structure for the report system, you can add your custom content here
    ?>
    <div class="report-system">
        <h1>Report System</h1>
        <!-- Add any report form or functionality here -->
        <form method="post" action="">
            <label for="report_title">Title:</label>
            <input type="text" id="report_title" name="report_title" required>
            <br>
            <label for="report_description">Description:</label>
            <textarea id="report_description" name="report_description" required></textarea>
            <br>
            <input type="submit" name="submit_report" value="Submit Report">
        </form>
    </div>
    <?php

    return ob_get_clean(); // Get the content generated by the buffer and return it
}

// Register the shortcode
add_shortcode('report_system', 'report_system_shortcode');
?>
